name: deploy-release
on:
  push:
    tags:
      - v*
jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Build Distributable
        run: ./gradlew.bat desktop:createDistributable
      - name: Build Exe
        run: ./gradlew.bat desktop:packageExe
      - name: Zip AndroidTool.zip
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'AndroidTool.zip'
          path: 'desktop/build/compose/binaries/main/app'
      - name: Zip AndroidTool.exe.zip
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'AndroidTool.exe.zip'
          path: 'desktop/build/compose/binaries/main/exe'

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: New Release.
          draft: false
          prerelease: false
          files: |
            AndroidTool.zip
            AndroidTool.exe.zip
